BIO_SUBHEADINGS=("botany" "cell biology" "computational biology" "cryobiology" "developmental biology" "ecology" "exobiology" "genetics" "laboratory animal science" "microbiology" "natural history" "neurobiology" "parasitology" "photobiology" "radiobiology" "sociobiology" "synthetic biology" "zoology")
INFORMATICS=("cheminformatics" "computational biology" "consumer health informatics" "dental informatics" "medical informatics" "nursing informatics" "public health informatics")
ALGORITHMS=("artificial intelligence" "latent class analysis" "cellular automata")

#MESH_PARSED=("Anatomy" "Histocytochemistry" "Immunochemistry" "Molecular Biology" "Proteomics" "Metabolomics" "Human Genetics" "Genetics Population" "Genetic Research" "Food Microbiology" "Soil Microbiology" "Water Microbiology" "Computational Biology" "Biophysics" "Biotechnology" "Neurosciences" "Pharmacology" "Physiology" "Toxicology" "Chemistry Pharmaceutical" "Crystallography" "Electrochemistry" "Photochemistry" "Statistics as Topic" "Nonlinear Dynamics" "Acoustics" "Electronics" "Magnetics" "Nuclear Physics" "Rheology" "Fiber Optic Technology" "Microscopy" "Operations Research" "Research Design" "Health Services Research" "Nursing Evaluation Research" "Nursing Methodology Research" "Outcome Assessment Health Care" "Translational Research Biomedical" "Empirical Research" "Nanotechnology" "Microtechnology" "Ecology" "Geography" "Paleontology")
MESH_PARSED=("Classification" "Scholarly Communication" "Advertising" "Diffusion of Innovation" "Nonverbal Communication" "Disclosure" "Information Dissemination" "Mass Media" "Books" "Review Literature as Topic" "Serial Publications" "Teaching Materials" "Telemetry" "Telephone" "Telemedicine" "Social Media" "Supervised Machine Learning" "Deep Learning" "Neural Networks Computer" "Knowledge Bases" "Electronic Data Processing" "Computer Graphics" "Molecular Dynamics Simulation" "Molecular Docking Simulation" "Computer Communication Networks" "Computers" "Image Enhancement" "Imaging Three-Dimensional" "Mathematical Computing" "Signal Processing Computer-Assisted" "Software" "Tape Recording" "Video Recording" "Data Display" "Bibliographies as Topic" "Amino Acid Sequence" "Base Sequence" "Carbohydrate Sequence" "Molecular Sequence Annotation" "Diagnostic and Statistical Manual of Mental Disorders" "Biological Ontologies" "Reading" "Speech" "Writing" "Terminology as Topic" "Phonetics" "Semantics" "Vocabulary" "Publishing" "Feedback" "Monte Carlo Method" "Databases Bibliographic" "Databases Genetic" "Databases Chemical" "Interviews as Topic" "Records" "Pattern Recognition Automated" "Diagnosis Computer-Assisted" "Radiotherapy Planning Computer-Assisted" "Radiotherapy Conformal" "Decision Support Techniques" "Online Systems" "Medical Records Systems Computerized" "Computational Biology" "Anatomy" "Histocytochemistry" "Immunochemistry" "Molecular Biology" "Proteomics" "Metabolomics" "Human Genetics" "Genetics Population" "Genomics" "Genetic Research" "Food Microbiology" "Soil Microbiology" "Water Microbiology" "Biophysics" "Biotechnology" "Neurosciences" "Pharmacology" "Physiology" "Toxicology" "Chemistry Pharmaceutical" "Crystallography" "Electrochemistry" "Photochemistry" "Statistics as Topic" "Nonlinear Dynamics" "Acoustics" "Electronics" "Magnetics" "Nuclear Physics" "Rheology" "Fiber Optic Technology" "Microscopy" "Research Design" "Health Services Research" "Nursing Evaluation Research" "Nursing Methodology Research" "Outcome Assessment Health Care" "Translational Research Biomedical" "Empirical Research" "Nanotechnology" "Microtechnology" "Ecology" "Geography" "Paleontology")

python indices/download_article_metadata.py --key_file ncbi_api_key.txt

